### ISSUE TITLE
Медицинский борг сломан

### ISSUE THREAD

**Issue by StarRuCat** [MysticalFaceLesS/Shiptest#713]
Issue reported from  Round ID: 1407 ([RU] Celadon Shiptest: Alpha)

Reporting client version: 514.1589

Все модули медицинского борга не взаимодействуют с другими мобами, кроме шприца

![image](https://github.com/CeladonSS13/Shiptest/assets/27018085/c0acd6bb-37b1-41d6-9353-89110ddc3175)

**Comment by StarRuCat** [comment]
И, да, это касается боргов в целом - подавляющее большинство их модулей не может взаимодействовать с другими мобами

**Comment by MysticalFaceLesS** [comment]
> И, да, это касается боргов в целом - подавляющее большинство их модулей не может взаимодействовать с другими мобами

Данная ошибка уже была исправлена оффами https://github.com/CeladonSS13/Shiptest/pull/788/files и в данный момент фикс уже находится на сервере Beta.
